### ISSUE TITLE
AMD Radeon 7000 Series - Unhandled Exception on game launch

### ISSUE THREAD

**Issue by GabrielCoetzee** [xenia-canary/xenia-canary#130] opened 2023-02-15 20:38 UTC
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

As soon as I try to launch a game with Xenia (in my case I've tried Red Dead Redemption), I'm met with an immediate crash with these two dialogs: 

![image](https://user-images.githubusercontent.com/30634129/219148144-90cd488a-a918-45b1-a302-3645a339ed16.png)

I've done quite a bit of digging on this to see if I can resolve it myself or at least get an answer, and the closest I've come to getting an answer was spotting another user on the discord server that also has a 7900 XT that has the same issue. I understand this might be on AMD's side but I figured I'd still log it here, just in case it turns out to be something requiring implementation on Xenia's side as well. If this turns out to not be the case, please feel free to close or remove this issue.

### Describe what should happen

As per my understanding, the game should at least launch and open up. 

### If applicable, provide a callstack here, especially for crashes

Faulting application name: xenia_canary.exe, version: 0.0.0.0, time stamp: 0x63e7d361
Faulting module name: amdxc64.dll, version: 31.0.14001.45012, time stamp: 0x63e6de09
Exception code: 0xc0000005
Fault offset: 0x0000000000cba768
Faulting process id: 0x0x3BC8
Faulting application start time: 0x0x1D9417CCE7E07AA
Faulting application path: <Omitted>\Xenia\xenia_canary\xenia_canary.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\u0388153.inf_amd64_a09a6ed88273e4ec\B388275\amdxc64.dll
Report Id: 4984d87b-3261-4e01-9bd5-60f6e6469882
Faulting package full name: 
Faulting package-relative application ID: 

### If applicable, upload a logfile and link it here

[xenia.log](https://github.com/xenia-canary/xenia-canary/files/10747352/xenia.log)

**Comment by Gliniak** [comment] 2023-02-15 20:42
Duplicate of #129

**Closed as not planned by Gliniak** 2023-02-15 20:42 UTC
Labels: duplicate
